version: '3.8'

services:

  nodeserver:
    build:
      context: ./src
    container_name: nodeserver
    image: gabrielrosin/node-simple-app
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    tty: true
    networks:
      - nodejs-network
    # depends_on: [ db ]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: gabrielrosin/nginx-node
    container_name: nginx
    # entrypoint: dockerize -wait tcp://nodeserver:3000 -timeout 60s docker-entrypoint.sh
    networks:
      - nodejs-network
    ports:
      - "8080:80"
    depends_on: [ nodeserver ]
    # db:
    #   image: mysql:5.7
    #   command: --innodb-use-native-aio=0
    #   container_name: db
    #   restart: always
    #   tty: true
    #   volumes:
    #     - ./mysql:/var/lib/mysql
    #   environment:
    #     - MYSQL_DATABASE=nodejs-docker
    #     - MYSQL_ROOT_PASSWORD=root
    #   networks:
    #     - nodejs-network

networks:
  nodejs-network:
    driver: bridge
